### ISSUE TITLE
Cuda implementation

### ISSUE THREAD

**Issue by rey2019** [aspuru-guzik-group/Pasithea#3]
Hi, I'm a noob when it comes to pytorch and cuda. I was trying to run your code with cuda on my system, but I always get the "Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!" error at the end. I've double checked the model and the tensors, and they all seem to be on GPU, I've been looking at this for a while and I can't figure out how to run this using cuda. I really appreciate it if you could reply to me and give me some advice on what to check/do next. Thank you so much for your time
![Screenshot 2021-10-06 235007](https://user-images.githubusercontent.com/39713964/136317364-47a20321-c0f1-4432-ad47-a5629ce0ba88.png)
e!

**Comment by adiv5** [comment]
@rey2019  Just replace `newhot=hot+ upper_bound*rand(hot.shape)` with `newhot=torch.tensor(hot,device='cuda:0',dtype=torch.float)+ upper_bound*rand(hot.shape)`


the idea being `hot` is not a tensor, so we convert it to one and set its device as GPU(cuda:0) or if you dont have one, just replace  'cuda:0'  with 'cpu:0'

**Comment by rey2019** [comment]
@adiv5 So sorry I forgot to reply back. Your suggestion fixed the issue. Thank you so much! Im gonna close this now
